name: Sync upstream ZKstack CLI

on:
  schedule:
    - cron: "23 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: matter-labs/zksync-era
      SUBDIR: zkstack_cli
    steps:
      # 1. Clone mirror
      - name: Checkout mirror
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_PUSH }}
          fetch-depth: 0

      # 2. Fetch upstream repo
      - name: Fetch upstream source
        run: |
          git clone --depth 1 https://github.com/${UPSTREAM_REPO}.git upstream-src

      # 3. Create a sync branch
      - name: Prepare sync branch
        run: |
          BRANCH=sync/upstream-$(date -u +%Y%m%d)
          git switch -c "$BRANCH" || git switch "$BRANCH"
          # wipe current work tree (but keep .git)
          git rm -rf .
          # copy CLI crate into repo root
          rsync -a --delete --exclude '.git' upstream-src/${SUBDIR}/ .
          # remove any stray Cargo.lock created by rsync of parent dirs
          rm -f Cargo.lock

      # 4. Commit if there are changes
      - name: Commit changes (if any)
        id: commit
        run: |
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: sync upstream CLI $(date -Iseconds)"
            git push -u origin HEAD
            echo "committed=true" >> "$GITHUB_OUTPUT"
          else
            echo "No upstream changes"
          fi
        env:
          GIT_AUTHOR_NAME: mirror-bot
          GIT_AUTHOR_EMAIL: mirror-bot@example.com
          GIT_COMMITTER_NAME: mirror-bot
          GIT_COMMITTER_EMAIL: mirror-bot@example.com

      # 5. Open or update PR
      - name: Create / update PR
        if: steps.commit.outputs.committed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_PUSH }}
          branch: ${{ github.ref_name }}
          title: "Sync upstream ZKstack CLI"
          body: |
            Automated copy of `${{ env.SUBDIR }}` from `${{ env.UPSTREAM_REPO }}`.
            Review, then **Squash & Merge** to refresh the mirror.
          draft: false
